#!/bin/sh
set -ex

go get -v ./internal/cmd/mkengine-version

pkg="github.com/measurement-kit/engine/mobile/android/engine"
v=`${GOPATH}/bin/mkengine-version`
engine=mkengine-${v}.aar

git rm -rf mobile/android/engine/*.go
install -d mobile/android/engine

echo '// +build: android' > mobile/android/engine/collector.go
echo '' >> mobile/android/engine/collector.go
echo "// AUTOGENERATED BY $0; DO NOT EDIT" >> mobile/android/engine/collector.go
echo '' >> mobile/android/engine/collector.go
cat collector.go |                                                             \
  sed -e 's/Good/IsGood/g'                                                     \
      -e 's/Logs/GetLogs/g'                                                    \
      -e 's/UpdatedReportID/GetUpdatedReportID/g'                              \
      -e 's/UpdatedSerializedMeasurement/GetUpdatedSerializedMeasurement/g'    \
  >> mobile/android/engine/collector.go

git add mobile/android/engine

time gomobile bind      \
  -target android       \
  -o ${engine}          \
  -ldflags="-s -w"      \
  -tags="android ${1}"  \
  ${pkg}
