#!/bin/sh
set -ex

go get -v ./internal/cmd/mkengine-version

pkg="github.com/measurement-kit/engine/mobile/ios/MKEngine"
v=`${GOPATH}/bin/mkengine-version`
engine=MKEngine.framework

git rm -rf mobile/ios/MKEngine/*.go
install -d mobile/ios/MKEngine

echo '// +build: ios' > mobile/ios/MKEngine/collector.go
echo '' >> mobile/ios/MKEngine/collector.go
echo "// AUTOGENERATED BY $0; DO NOT EDIT" >> mobile/ios/MKEngine/collector.go
echo '' >> mobile/ios/MKEngine/collector.go
cat collector.go |                                                             \
  sed -e 's/package engine/package MKEngine/g'                                 \
  >> mobile/ios/MKEngine/collector.go

git add mobile/ios/MKEngine

time gomobile bind  \
  -target ios       \
  -o ${engine}      \
  -ldflags="-s -w"  \
  -tags="ios ${1}"  \
  ${pkg}

tarball=MKEngine-${v}.framework.tar
tar -cvf ${tarball} ${engine}
gzip -9 ${tarball}
