// +build ios

package MKEngine

import "github.com/measurement-kit/engine/collector"

// Contains the results of resubmitting a report.
type CollectorSubmitResults struct {
	rr collector.SubmitResults
}

// Returns whether the resubmission succeded.
func (rr *CollectorSubmitResults) Good() bool {
	return rr.rr.Good
}

// Returns the updated measurement.
func (rr *CollectorSubmitResults) UpdatedSerializedMeasurement() string {
	return rr.rr.UpdatedSerializedMeasurement
}

// Returns the updated report ID.
func (rr *CollectorSubmitResults) UpdatedReportID() string {
	return rr.rr.UpdatedReportID
}

// Returns logs generated by resubmitting a report.
func (rr *CollectorSubmitResults) Logs() string {
	return rr.rr.Logs
}

// Contains the settings for resubmitting a report.
type CollectorSubmitTask struct {
	rs collector.SubmitTask
}

// Sets the measurement to resubmit.
func (rs *CollectorSubmitTask) SetSerializedMeasurement(value string) {
	rs.rs.SerializedMeasurement = value
}

// Sets the timeout (in seconds) for the resubmission.
func (rs *CollectorSubmitTask) SetTimeout(value int64) {
	rs.rs.Timeout = value
}

// The task for resubmitting measurements.
type CollectorSubmitTask struct {
}

// Runs the resubmission task with specific settings and returns the results.
func (rt *CollectorSubmitTask) Run(rs *CollectorSubmitTask) *CollectorSubmitResults {
	var rr CollectorSubmitResults
	collector.SubmitInto(&rs.rs, &rr.rr)
	return &rr
}
