// +build ios

package MKEngine

import (
	"github.com/measurement-kit/engine/geoip"
)

// Contains the results of a GeoIP lookup.
type GeoIPLookupResults struct {
	lr geoip.LookupResults
}

// Returns whether the GeoIP lookup succeded.
func (lr *GeoIPLookupResults) Good() bool {
	return lr.lr.Good
}

// Returns the discovered probe IP.
func (lr *GeoIPLookupResults) ProbeIP() string {
	return lr.lr.ProbeIP
}

// Returns the discovered probe ASN.
func (lr *GeoIPLookupResults) ProbeASN() string {
	return lr.lr.ProbeASN
}

// Returns the discovered probe CC.
func (lr *GeoIPLookupResults) ProbeCC() string {
	return lr.lr.ProbeCC
}

// Returns the discovered probe org.
func (lr *GeoIPLookupResults) ProbeOrg() string {
	return lr.lr.ProbeOrg
}

// Returns logs generated by the GeoIP lookup.
func (lr *GeoIPLookupResults) Logs() string {
	return lr.lr.Logs
}

// GeoIPLookupSettings contains the GeoIP lookup settings.
type GeoIPLookupSettings struct {
	ls geoip.LookupSettings
}

// Sets the timeout (in seconds) for the GeoIP lookup.
func (ls *GeoIPLookupSettings) SetTimeout(value int64) {
	ls.ls.Timeout = value
}

// Sets the directory in which to download MMDB databases if needed.
func (ls *GeoIPLookupSettings) SetWorkDirPath(value string) {
	ls.ls.WorkDirPath = value
}

// The GeoIP lookup task.
type GeoIPLookupTask struct {
}

// Runs the GeoIP lookup task with specific settings and returns the results.
func (lt *GeoIPLookupTask) Run(ls *GeoIPLookupSettings) *GeoIPLookupResults {
	var lr GeoIPLookupResults
	geoip.LookupInto(&ls.ls, &lr.lr)
	return &lr
}
