// +build android

package engine

import "github.com/measurement-kit/engine/collector"

// Contains the results of resubmitting a report.
type MKECollectorResubmitResults struct {
	rr collector.ResubmitResults
}

// Returns whether the resubmission succeded.
func (rr *MKECollectorResubmitResults) Good() bool {
	return rr.rr.Good
}

// Returns the updated measurement.
func (rr *MKECollectorResubmitResults) UpdatedSerializedMeasurement() string {
	return rr.rr.UpdatedSerializedMeasurement
}

// Returns the updated report ID.
func (rr *MKECollectorResubmitResults) UpdatedReportID() string {
	return rr.rr.UpdatedReportID
}

// Returns logs generated by resubmitting a report.
func (rr *MKECollectorResubmitResults) Logs() string {
	return rr.rr.Logs
}

// Contains the settings for resubmitting a report.
type MKECollectorResubmitSettings struct {
	rs collector.ResubmitSettings
}

// Sets the measurement to resubmit.
func (rs *MKECollectorResubmitSettings) SetSerializedMeasurement(value string) {
	rs.rs.SerializedMeasurement = value
}

// Sets the timeout (in seconds) for the resubmission.
func (rs *MKECollectorResubmitSettings) SetTimeout(value int64) {
	rs.rs.Timeout = value
}

// The task for resubmitting measurements.
type MKECollectorResubmitTask struct {
}

// Runs the resubmission task with specific settings and returns the results.
func (rt *MKECollectorResubmitTask) Run(rs *MKECollectorResubmitSettings) *MKECollectorResubmitResults {
	var rr MKECollectorResubmitResults
	collector.ResubmitInto(&rs.rs, &rr.rr)
	return &rr
}
