// +build android

package engine

import (
	"github.com/measurement-kit/engine/geoip"
)

// Contains the results of a GeoIP lookup.
type MKEGeoIPLookupResults struct {
	lr geoip.LookupResults
}

// Returns whether the GeoIP lookup succeded.
func (lr *MKEGeoIPLookupResults) Good() bool {
	return lr.lr.Good
}

// Returns the discovered probe IP.
func (lr *MKEGeoIPLookupResults) ProbeIP() string {
	return lr.lr.ProbeIP
}

// Returns the discovered probe ASN.
func (lr *MKEGeoIPLookupResults) ProbeASN() string {
	return lr.lr.ProbeASN
}

// Returns the discovered probe CC.
func (lr *MKEGeoIPLookupResults) ProbeCC() string {
	return lr.lr.ProbeCC
}

// Returns the discovered probe org.
func (lr *MKEGeoIPLookupResults) ProbeOrg() string {
	return lr.lr.ProbeOrg
}

// Returns logs generated by the GeoIP lookup.
func (lr *MKEGeoIPLookupResults) Logs() string {
	return lr.lr.Logs
}

// Contains the GeoIP lookup settings.
type MKEGeoIPLookupSettings struct {
	ls geoip.LookupSettings
}

// Sets the timeout (in seconds) for the GeoIP lookup.
func (ls *MKEGeoIPLookupSettings) SetTimeout(value int64) {
	ls.ls.Timeout = value
}

// Sets the directory in which to download MMDB databases if needed.
func (ls *MKEGeoIPLookupSettings) SetWorkDirPath(value string) {
	ls.ls.WorkDirPath = value
}

// The GeoIP lookup task.
type MKEGeoIPLookupTask struct {
}

// Runs the GeoIP lookup task with specific settings and returns the results.
func (lt *MKEGeoIPLookupTask) Run(ls *MKEGeoIPLookupSettings) *MKEGeoIPLookupResults {
	var lr MKEGeoIPLookupResults
	geoip.LookupInto(&ls.ls, &lr.lr)
	return &lr
}
